In [13]:
import pandas as pd
import numpy as np
from datetime import timedelta, datetime

In [14]:
np.random.seed(42)
# Generate dummy data for two days (48 hours)
start_time = pd.to_datetime('2023-12-21 00:00:00')
end_time = start_time + pd.Timedelta(days=2, hours=23)

time_range = pd.date_range(start=start_time, end=end_time, freq='H')

# Generate random data for temperature, humidity, and CO
data = {
    'Time': time_range,
    'Temperature (C)': np.random.uniform(18, 25, len(time_range)),
    'Humidity (%)': np.random.uniform(40, 70, len(time_range)),
    'CO (ppm)': np.random.uniform(0, 5, len(time_range))
}

# Create a DataFrame
df = pd.DataFrame(data)

In [15]:
df

                  Time  Temperature (C)  Humidity (%)  CO (ppm)
0  2023-12-21 00:00:00        20.621781     40.165664  1.424202
1  2023-12-21 01:00:00        24.655000     64.463843  0.184435
2  2023-12-21 02:00:00        23.123958     61.205720  3.047822
3  2023-12-21 03:00:00        22.190609     61.870215  2.513395
4  2023-12-21 04:00:00        19.092130     63.138110  0.257394
..                 ...              ...           ...       ...
67 2023-12-23 19:00:00        23.615379     69.153462  3.459476
68 2023-12-23 20:00:00        18.521855     68.873419  3.259806
69 2023-12-23 21:00:00        24.908209     47.553469  1.121347
70 2023-12-23 22:00:00        23.405713     54.917455  3.560896
71 2023-12-23 23:00:00        19.391010     49.026349  1.186245

[72 rows x 4 columns]

In [16]:
excel_path = "./data.xlsx"
df.to_excel(excel_path)

In [17]:
# ##Installing plotly, flask
# !pip install plotly
# !pip install flask